import type { AffiliateProviderDefinition } from "./types";

export const affiliateProviders: AffiliateProviderDefinition[] = [
  {
    id: "awin",
    name: "Awin",
    status: "ready_after_account",
    integration: "api_or_feed",
    auth: "api_key",
    supports: {
      products: true,
      prices: true,
      images: true,
      availability: true,
      coupons: true,
      affiliateLinks: true,
      reporting: true,
    },
    notes: [
      "Strong first integration for a comparison/deals platform.",
      "Publisher product feeds include deep links, product names, prices, images and stock fields.",
      "Keep feed/API credentials server-side only.",
    ],
  },
  {
    id: "cj",
    name: "CJ Affiliate",
    status: "ready_after_account",
    integration: "api_or_feed",
    auth: "bearer",
    supports: {
      products: true,
      prices: true,
      images: true,
      availability: true,
      coupons: true,
      affiliateLinks: true,
      reporting: true,
    },
    notes: [
      "Publisher Product Feed API can search products by price, currency, country and other criteria.",
      "Good source for adding multiple advertisers behind one adapter.",
    ],
  },
  {
    id: "rakuten",
    name: "Rakuten Advertising",
    status: "ready_after_account",
    integration: "api",
    auth: "bearer",
    supports: {
      products: true,
      prices: true,
      images: true,
      availability: false,
      coupons: true,
      affiliateLinks: true,
      reporting: true,
    },
    notes: [
      "Product Search API returns product name, price, sale price, descriptions, image and tracked product link.",
      "Coupon Feed API is separate and should feed the same normalized offer layer.",
    ],
  },
  {
    id: "admitad",
    name: "Admitad",
    status: "ready_after_account",
    integration: "feed",
    auth: "account_specific",
    supports: {
      products: true,
      prices: true,
      images: true,
      availability: true,
      coupons: true,
      affiliateLinks: true,
      reporting: true,
    },
    notes: [
      "XML product feeds are designed for affiliate sites/apps and can carry current product data at scale.",
      "Useful for broad merchant coverage without one direct integration per store.",
    ],
  },
  {
    id: "noon",
    name: "noon Affiliate",
    status: "affiliate_available_api_pending",
    integration: "api_or_feed",
    auth: "pending",
    supports: {
      products: false,
      prices: false,
      images: false,
      availability: false,
      coupons: true,
      affiliateLinks: true,
      reporting: true,
    },
    notes: [
      "Official affiliate program is available.",
      "Public product-catalog API/feed documentation has not yet been verified; request feed/API access after account approval.",
    ],
  },
  {
    id: "impact",
    name: "impact.com",
    status: "client_only_docs",
    integration: "api",
    auth: "account_specific",
    supports: {
      products: true,
      prices: true,
      images: true,
      availability: true,
      coupons: true,
      affiliateLinks: true,
      reporting: true,
    },
    notes: [
      "Partner APIs are available to current platform clients.",
      "Developer documentation requires account access, so implementation starts after credentials are issued.",
    ],
  },
];
